apiVersion: apps/v1
kind: Deployment
metadata:
  name: assets-project-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assets
  template:
    metadata:
      labels:
        app: assets
    spec:
      containers:
        - name: assets
          image: diargal0307/assets-project:v1
          ports:
            - containerPort: 8080
